/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Join the Discord!": "加入 Discord!",
    "Fix export button and save": "修复导出按钮和保存",
    "ENABLED": "启用",
    "Export to file": "导出为文件",
    "Import clipboard": "从剪贴板导入",
    "Import file": "从文件导入",
    "DISABLED": "禁用",
    "Experience": "经验值",
    "Cancel": "取消",
    "There are 5000 collectibles you can collect, each with their own rarity and a gold per second value based on that. You get 1 chest every 10 minutes to start with, with max 30 at a time, but you can increase this limit in the Upgrades. You can get Event Vouchers and Max Potions from chests at a 0.5% rate with a pity counter set to 200, so make sure to open these when you can.": "你可以收集5000件收藏品，每件都有自己的稀有性和每秒金币值。一开始你每10分钟获得1个箱子，一次最多30个，但你可以在升级中增加这个限制。你可以以0.5%的价格从箱子里获得活动券和最大药水，怜悯计数器设置为200，所以一定要在你可以的时候打开这些。",
    "There are 5000 collectibles you can collect, each with their own rarity and a gold per second value based on that. You get 1 chest every 10 minutes \n                to start with, with max 30 at a time, but you can increase this limit in the Upgrades. You can get Event Vouchers and Max Potions from chests at a \n                0.5% rate with a pity counter set to 200, so make sure to open these when you can.": "你可以收集5000件收藏品，每件都有自己的稀有性和每秒金币值。一开始你每10分钟获得1个箱子，一次最多30个，但你可以在升级中增加这个限制。你可以以0.5%的价格从箱子里获得活动券和最大药水，怜悯计数器设置为200，所以一定要在你可以的时候打开这些。",
    "Help": "帮助",
    "Filters:": "过滤器:",
    "Export Save": "导出存档",
    "Events": "活动",
    "Event Area": "活动区域",
    "Epic": "史诗",
    "Data Export": "数据导出",
    "Crit Chance": "暴击率",
    "Cost:": "成本:",
    "Collection": "收藏品",
    "Common": "普通",
    "Capacity": "容量",
    "Buy upgrades with Research Points and Gold. You gain 0.1 Research Point per second from each party member and then 0.1-0.5 Research Points per second from released Dreamlings, depending on the rarity. Once you have accumulated some Dream Points, you could buy cheap Common T1's from the Dream Book for 100k each and release them for 0.1 Research Points per second. Gold comes from collectibles, which you get from chests in the Collection tab.": "用研究点数和金币购买升级。你从每个队友身上每秒获得0.1点研究点，然后从释放的梦境者身上每秒获得0.1-0.5点研究点，这取决于稀有程度。一旦你积累了一些梦点，你就可以从梦书中购买便宜的普通T1，每个10万，每秒0.1个研究点。金币来自收藏品，你可以从收藏品选项卡的箱子中获得。",
    "Buy upgrades with Research Points and Gold. You gain 0.1 Research Point per second from each party member and then 0.1-0.5 Research Points per second from \n                released Dreamlings, depending on the rarity. Once you have accumulated some Dream Points, you could buy cheap Common T1's from the Dream Book for 100k \n                each and release them for 0.1 Research Points per second. Gold comes from collectibles, which you get from chests in the Collection tab.": "用研究点数和金币购买升级。你从每个队友身上每秒获得0.1点研究点，然后从释放的梦境者身上每秒获得0.1-0.5点研究点，这取决于稀有程度。一旦你积累了一些梦点，你就可以从梦书中购买便宜的普通T1，每个10万，每秒0.1个研究点。金币来自收藏品，你可以从收藏品选项卡的箱子中获得。",
    "Buy consumables with Quest Tokens. The effects are immediately applied, so if for example you buy 6h event access, you get it immediately. The chests you purchase will be in the Collection tab, same as other chests. You can only have one temporary boost running at a time!": "用任务代币购买消耗品。效果是立即应用的，因此，例如，如果您购买了6小时事件访问权，您将立即获得效果。你购买的箱子和其他箱子一样会出现在“收藏”选项卡中。你只能有一个临时增强运行在一个时间！",
    "Buy consumables with Quest Tokens. The effects are immediately applied, so if for example you buy 6h event access, you get it immediately. The \n                chests you purchase will be in the Collection tab, same as other chests. You can only have one temporary boost running at a time!": "用任务代币购买消耗品。效果是立即应用的，因此，例如，如果您购买了6小时事件访问权，您将立即获得效果。你购买的箱子和其他箱子一样会出现在“收藏”选项卡中。你只能有一个临时增强运行在一个时间！",
    "Level": "等级",
    "Legendary": "传说",
    "Import Save": "导入存档",
    "Instant Tame": "即时驯服",
    "Open 30 Chests": "打开 30 宝箱",
    "Quests": "任务",
    "Rank": "层级",
    "Rare": "稀有",
    "Rarity": "稀有度",
    "Rarity:": "稀有度:",
    "Save Files": "保存文件",
    "Upgrade": "升级",
    "Upgrades": "升级",
    "Upgrades Tab": "升级标签页",
    "Wild Areas": "野外区域",
    "Wild Areas Tab": "野外区域标签页",
    "Uncommon": "罕见",
    "Forest": "森林",
    "Stars": "星星",
    "Storage": "存储",
    "Storage (Level 25+ only)": "存储 (仅限等级 25+)",
    "Taming Speed": "驯服速度",
    "Token Shop": "代币商店",
    "Training": "训练",
    "Traded": "交易",
    "Trading": "交易",
    "Trophy Hall": "奖杯陈列厅",
    "Welcome to Dreamlings Idle, a buggy text-based creature collector that is all about waiting. The majority, but not all, of this game was created\n                with tremendous help from several AIs. For this reason, because the dev is not actually a dev but just someone who has a hoarding problem, it is\n                probably rather buggy. There are also no images in this game, but there are a few emojis. Does that count? No, suppose not.": "欢迎来到 梦境生物放置，这是一款充满bug的基于文本的生物收集软件，一切都是关于等待。这款游戏的大部分（但不是全部）都是在几个ai的大力帮助下创造出来的。出于这个原因，因为开发人员实际上并不是一个开发人员，而只是一个有囤积问题的人，所以它可能有相当多的bug。这个游戏也没有图片，但是有一些表情符号。这算吗？不，假设不是。",
    "When you have level 25 Dreamlings that have the same rarity and tier, you can fuse them. Upon success you will get a higher tier, a higher rarity or both. The selected Dreamlings will disappear and the result will appear in your storage, starting over at level 1. Failure to fuse will make the Dreamlings tired and mean you will have to wait 30 minutes to try again. You are able to get star Dreamlings from regular fusion. Fusing a star and a regular Dreamling will result in a 50% chance of a star, while fusing two stars will always give another star.": "当你有25级的梦境生物，有相同的稀有性和层数，你可以融合他们。一旦成功，你将获得更高的等级，更高的稀有性或两者兼而有之。选中的梦境会消失，结果会显示在仓库中，从1级重新开始。失败的融合将使梦境生物疲劳，意味着你将不得不等待30分钟再试一次。你可以从常规的核聚变中得到带星梦境生物。融合一颗星星和一个普通的梦境生物会产生50%的星星，而融合两颗星星总是会产生另一颗星星。",
    "When you have level 25 Dreamlings that have the same rarity and tier, you can fuse them. Upon success you will get a higher tier, a higher rarity or both. \n                The selected Dreamlings will disappear and the result will appear in your storage, starting over at level 1. Failure to fuse will make the Dreamlings \n                tired and mean you will have to wait 30 minutes to try again. You are able to get star Dreamlings from regular fusion. Fusing a star and a regular \n                Dreamling will result in a 50% chance of a star, while fusing two stars will always give another star.": "当你有25级的梦境生物，有相同的稀有性和层数，你可以融合他们。一旦成功，你将获得更高的等级，更高的稀有性或两者兼而有之。选中的梦境会消失，结果会显示在仓库中，从1级重新开始。失败的融合将使梦境生物疲劳，意味着你将不得不等待30分钟再试一次。你可以从常规的核聚变中得到带星梦境生物。融合一颗星星和一个普通的梦境生物会产生50%的星星，而融合两颗星星总是会产生另一颗星星。",
    "Research Points": "研究点数",
    "Resource Gain": "资源增益",
    "Search for Dreamling": "搜索梦境生物",
    "Secret Upgrades & Other Stuff": "秘密升级 & 其他东西",
    "Shop": "商店",
    "Sort by:": "排序方式:",
    "Species": "特殊",
    "Special Dreamlings/Stars": "特殊 梦境生物/星星",
    "Buy": "购买",
    "Delete Save": "删除存档",
    "Chest Regen": "宝箱回复",
    "Collection/Chests": "收藏品/宝箱",
    "Dream Book": "梦境之书",
    "Dream Points": "梦境点数",
    "Dreamlings Tab": "梦境生物标签页",
    "Energy Regen": "能量回复",
    "Event": "活动",
    "Event Access (6h)": "活动参与（6小时）",
    "Double XP gained for 15 minutes.": "15分钟获得双倍经验值。",
    "Double research points gained for 15 minutes.": "15分钟内获得双倍研究点数。",
    "Gold": "金币",
    "Gold Boost": "金币提升",
    "Import Dreamling Card": "导入梦境生物卡片",
    "Join the Discord here!": "在这里加入 Discord!",
    "Instantly restore 5 energy.": "立即恢复5点能量。",
    "Instantly complete the current tame.": "立即完成当前驯服。",
    "Here live your current Dreamlings: your active party, your training Dreamlings and your storage. Party Dreamlings give bonuses and gain experience \n                every second. The Dreamlings you put in training gain twice the experience, but give no bonuses. The ones in your storage don't gain experience \n                and they don't give bonuses. You start with 500 storage, but you can increase your storage later. Every party member gives you 0.5 experience per \n                second, so try to keep a full party at all times.": "这里住着你现在的梦境生物：你的活动队伍，你的梦境生物训练和你的存储。队伍梦境生物每秒钟获得奖励和经验值。你训练的梦境生物可以获得两倍的经验值，但没有奖励。你的仓库里的人不会获得经验，也不会给予奖励。您开始使用500个存储空间，但以后可以增加存储空间。每个队伍成员每秒给你0.5点经验值，所以尽量保持一个完整的队伍。",
    "If you clicked away the popups meant to help you, here is what they said for you to read while you wait.": "如果你点击了那些旨在帮助你的弹出窗口，下面是他们说的话，让你在等待的时候阅读。 ",
    "Ranch": "牧场",
    "Max Training Size": "最大训练规模",
    "Max Party Size": "最大队伍规模",
    "Max Storage Size": "最大存储规模",
    "Max Quests": "最大任务",
    "Max Energy": "最大能量",
    "Max Chests": "最大宝箱",
    "Gameplay": "游戏玩法",
    "Fusion Lab": "融合实验室",
    "Fuse Dreamlings": "融合梦境生物",
    "Fusing two Legendary T5 Dreamlings will always result in a star Legendary T5. Get it to level 1000 with a Max Potion and then you get the option of ascending it. Ascension removes the Dreamling from regular gameplay, but adds it to the Trophy Hall and its boosts become permanent, as though you have it in your party. Normally Legendaries have their boosts capped at level 250, but with ascension this becomes level 333. Not only will you free up a party slot by ascending a star Legendary T5 Dreamling, you will also get higher boosts from them, which definitely makes it worth it.": "融合两个传说T5梦境生物将会产生一个星级传传说T5。用最大药水把它升到1000级，然后你可以选择转生它。转生从常规的游戏玩法中移除梦境生物，但将其添加到奖杯陈列室中，它的提升将变得永久，就好像你的队伍中有它一样。通常情况下，传说道具的增益上限是250级，但随着转生，这个上限可以达到333级。你不仅可以通过转生一个传说T5梦境生物星来释放一个队伍插槽，你还可以从中获得更高的增益，这绝对是值得的。",
    "Fusing two Legendary T5 Dreamlings will always result in a star Legendary T5. Get it to level 1000 with a Max Potion and then you get the option of \n                ascending it. Ascension removes the Dreamling from regular gameplay, but adds it to the Trophy Hall and its boosts become permanent, as though you \n                have it in your party. Normally Legendaries have their boosts capped at level 250, but with ascension this becomes level 333. Not only will you free \n                up a party slot by ascending a star Legendary T5 Dreamling, you will also get higher boosts from them, which definitely makes it worth it.": "融合两个传说T5梦境生物将会产生一个星级传传说T5。用最大药水把它升到1000级，然后你可以选择转生它。转生从常规的游戏玩法中移除梦境生物，但将其添加到奖杯陈列室中，它的提升将变得永久，就好像你的队伍中有它一样。通常情况下，传说道具的增益上限是250级，但随着转生，这个上限可以达到333级。你不仅可以通过转生一个传说T5梦境生物星来释放一个队伍插槽，你还可以从中获得更高的增益，这绝对是值得的。",
    "Export All Dreamlings to CSV": "导出所有梦境生物为CSV文件",
    "Export Dream Book to CSV": "导出梦境之书为CSV文件",
    "Exporting/Trading": "导出/交易",
    "Boost Upgrades": "提升升级",
    "Got it!": "知道了!",
    "Party Boosts": "队伍提升",
    "Party Dreamlings (": "队伍梦境生物 (",
    // "Acornlet, Amethis, Andante, Beamis, Bitelet, Blissful, Chamomis, Chiplet, Chipmunk, Chirpis, Clockwork, Cloudbreak, Coralette, Crowlet, Crumblet, Cursoris, Dopplet, Elfin, Finery, Foxlet, Grovekin, Gullwing, Hawklet, Jasmine, Jewelis, Jiggly, Lento, Minotlet, Moonbloom, Nightfall, Nutlet, Nymphlet, Pastrylet, Petalis, Pouris, Puffles, Robinlet, Sandstorm, Shellby, Soprano, Splashis, Stafflet, Stormlet, Streamlet, Sunspot, Timberling, Treblelet, Valleykin, Wirelis, Wonderis": "橡果（Acornlet）、阿梅西斯（Amethis）、行板（Andante）、光束（Beamis）、小咬（Bitelet）、幸福（Blissful）、甘菊（Chamomis）、小片（Chiplet）、花栗鼠（Chipmunk）、唧唧（Chirpis）、发条（Clockwork）、云破（Cloudbreak）、珊瑚（Coralette）、乌鸦（Crowlet）、碎屑（Crumblet）、光标（Cursoris）、多普勒（Dopplet）、精灵（Elfin）、华服（Finery）、狐狸（Foxlet）、林间小径（Grovekin）、鸥翼（Gullwing）、小鹰（Hawklet）、茉莉（Jasmine）、珠宝（Jewelis）、摇摆（Jiggly）、慢板（Lento）、米诺特（Minotlet）、月华（Moonbloom）、夜幕（Nightfall）、坚果（Nutlet）、仙女（Nymphlet）、糕点（Pastrylet）、花瓣（Petalis）、倾泻（Pouris）、蓬松（Puffles）、知更鸟（Robinlet）、沙尘暴（Sandstorm）、贝壳（Shellby）、女高音（Soprano）、飞溅（Splashis）、员工（Stafflet）、风暴（Stormlet）、溪流（Streamlet）、太阳黑子（Sunspot）、木材（Timberling）、高音（Treblelet）、山谷小径（Valleykin）、铁丝（Wirelis）、奇迹（Wonderis）",
    "Acornlet, Amethis, Andante, Beamis, Bitelet, Blissful, Chamomis, Chiplet, Chipmunk, Chirpis, Clockwork, Cloudbreak, Coralette, Crowlet, Crumblet, Cursoris, Dopplet, Elfin, Finery, Foxlet, Grovekin, Gullwing, Hawklet, Jasmine, Jewelis, Jiggly, Lento, Minotlet, Moonbloom, Nightfall, Nutlet, Nymphlet, Pastrylet, Petalis, Pouris, Puffles, Robinlet, Sandstorm, Shellby, Soprano, Splashis, Stafflet, Stormlet, Streamlet, Sunspot, Timberling, Treblelet, Valleykin, Wirelis, Wonderis": "Acornlet, Amethis, Andante, Beamis, Bitelet, Blissful, Chamomis, Chiplet, Chipmunk, Chirpis, Clockwork, Cloudbreak, Coralette, Crowlet, Crumblet, Cursoris, Dopplet, Elfin, Finery, Foxlet, Grovekin, Gullwing, Hawklet, Jasmine, Jewelis, Jiggly, Lento, Minotlet, Moonbloom, Nightfall, Nutlet, Nymphlet, Pastrylet, Petalis, Pouris, Puffles, Robinlet, Sandstorm, Shellby, Soprano, Splashis, Stafflet, Stormlet, Streamlet, Sunspot, Timberling, Treblelet, Valleykin, Wirelis, Wonderis",
    "Find 10 Event Collectibles": "找到10个活动收藏品",
    "Exporting creates a QR code (or, if that fails, a regular text code), which you can use to trade with other people. There is not much point in trading with yourself, because beyond a 'TRADED' banner and collection purposes, there are no benefits. The codes are valid for 24h after generation, so you can't just export everything and keep them indefinitely if you run out of storage. You can use the same code once every 24h, but you can use as many codes as you want. If you'd like to trade, check out the Discord link in the Settings tab and join us!": "导出会创建一个QR码（或者，如果失败，则是一个普通的文本代码），您可以使用它与其他人进行交易。与自己进行交易没有多大意义，因为除了“交易”横幅和收集目的之外，没有任何好处。代码在生成后24小时内有效，所以如果存储空间用完，您不能只是导出所有内容并无限期保留它们。您可以每24小时使用一次相同的代码，但您可以使用尽可能多的代码。如果您想交易，请查看设置选项卡中的Discord链接并加入我们！",
    "Every single Dreamling you have ever collected appears here. You can buy collected Dreamlings for Dream Points. The price depends on the rarity and the tier, and events are three times as expensive. This can help you finish a collection, if that's what you want to work on. The base rate for Dream Points is 1 per second, per party member. You are able to get star Dreamlings from Dream Book purchases.": "你收集的每一个梦境生物都出现在这里。你可以用梦境点数购买可收集的梦境生物。价格取决于稀有程度和层级，而活动的价格是前者的三倍。这可以帮助你完成一个集合，如果这是你想做的。每个队友每秒获得1点梦境点数。你可以通过购买梦境之书来获得星级梦境生物。",
    "Every single Dreamling you have ever collected appears here. You can buy collected Dreamlings for Dream Points. The price depends on the rarity and the \n                tier, and events are three times as expensive. This can help you finish a collection, if that's what you want to work on. The base rate for Dream Points \n                is 1 per second, per party member. You are able to get star Dreamlings from Dream Book purchases.": "你收集的每一个梦境生物都出现在这里。你可以用梦境点数购买可收集的梦境生物。价格取决于稀有程度和层级，而活动的价格是前者的三倍。这可以帮助你完成一个集合，如果这是你想做的。每个队友每秒获得1点梦境点数。你可以通过购买梦境之书来获得星级梦境生物。",
    "Every month, 30 new species are added that you can collect for that month only. These are limited edition for now, meaning they aren't set to return \n                afterwards, so get them while you can. If you're aiming to collect all of them, a tip is to collect at least the Common T1's of each and preferably \n                the Uncommon T1's as well, to make things easier on yourself. With the Dream Book and a lot of levelling and fusions and some luck, you will be able \n                to work your way up through every Dreamling species.": "每个月，30个新物种被添加，你只能在当月收集。这些都是限量版，这意味着它们不会被设置为返回\n，所以你可以得到它们。如果你的目标是收集所有这些，建议是至少收集每一个的普通T1，最好也收集罕见T1，让事情变得更容易。有了 梦境之书 和大量的升级和融合，再加上一些运气，你就可以通过每一个梦境生物来提升自己。",
    "Every month, 30 new species are added that you can collect for that month only. These are limited edition for now, meaning they aren't set to return afterwards, so get them while you can. If you're aiming to collect all of them, a tip is to collect at least the Common T1's of each and preferably the Uncommon T1's as well, to make things easier on yourself. With the Dream Book and a lot of levelling and fusions and some luck, you will be able to work your way up through every Dreamling species.": "每个月，30个新物种被添加，你只能在当月收集。这些都是限量版，这意味着它们不会被设置为返回\n，所以你可以得到它们。如果你的目标是收集所有这些，建议是至少收集每一个的普通T1，最好也收集罕见T1，让事情变得更容易。有了 梦境之书 和大量的升级和融合，再加上一些运气，你就可以通过每一个梦境生物来提升自己。",
    "Exporting creates a QR code (or, if that fails, a regular text code), which you can use to trade with other people. There is not much point in trading \n                with yourself, because beyond a \"TRADED\" banner and collection purposes, there are no benefits. The codes are valid for 24h after generation, so you \n                can't just export everything and keep them indefinitely if you run out of storage. You can use the same code once every 24h, but you can use as many \n                codes as you want. If you'd like to trade, check out the Discord link in the Settings tab and join us!": "导出会创建一个QR码（或者，如果失败，则是一个普通的文本代码），您可以使用它与其他人进行交易。与自己交易没有多大意义，因为除了“交易”横幅和收集目的之外，没有任何好处。代码在生成后24小时内有效，所以如果存储空间用完，您不能只是导出所有内容并无限期保留它们。您可以每24小时使用一次相同的代码，但您可以使用尽可能多的代码。如果您想交易，请查看设置选项卡中的Discord链接并加入我们！",
    "Every day you get 5 quests, which are repeatable 5 times. Progress doesn't carry over between repeats, so claim them immediately. You get Quest Tokens from every completed quest and a small bit of gold that is mostly meant to help you get started on the Upgrades rather than provide you with a proper amount.": "每天你会得到5个任务，这些任务可以重复5次。进展不会在重复之间延续，所以要立即申请。你可以从每个完成的任务中获得任务代币和一小部分金币，这主要是为了帮助你开始升级，而不是提供给你适当的数量。",
    "Every day you get 5 quests, which are repeatable 5 times. Progress doesn't carry over between repeats, so claim them immediately. You get Quest Tokens \n                from every completed quest and a small bit of gold that is mostly meant to help you get started on the Upgrades rather than provide you with a proper \n                amount.": "每天你会得到5个任务，这些任务可以重复5次。进展不会在重复之间延续，所以要立即申请。你可以从每个完成的任务中获得任务代币和一小部分金币，这主要是为了帮助你开始升级，而不是提供给你适当的数量。",
    "Party Dreamlings give bonuses and gain experience every second. The Dreamlings you put in training gain twice the experience, but give no bonuses. The ones in your storage don't gain experience and they don't give bonuses. You start with 500 storage, but you can increase your storage later. Every party member gives you 0.5 experience per second, so try to keep a full party at all times.": "队伍里的梦境生物每秒钟获得奖励和经验值。你训练的梦境生物可以获得两倍的经验值，但没有奖励。你的仓库里的人不会获得经验，也不会给予奖励。您开始使用500个存储空间，但以后可以增加存储空间。每个团队成员每秒给你0.5点经验值，所以尽量保持一个完整的队伍。",
    "You start with the Forest area, where you can find ~50 random Dreamlings out of the 650 base ones. These are different for everyone. You will need \n                Event Vouchers to temporarily access the Event area, or purchase access from the Token Shop with Quest Tokens. Search for a wild Dreamling, which costs \n                1 energy, and then click \"tame\". Taming takes some time, depending on the rarity. You can only tame 1 at a time, so choose carefully. Wild Dreamlings \n                will disappear after some time (10-15 minutes), so don't spend all your energy at once unless you plan on leaving for a while and letting it regenerate. \n                Energy regens 1 every 10 minutes and starts off with max 30, but you can increase this.": "你可以从 森林 区域开始，在那里你可以从650个基础梦境生物中找到大约50个随机的梦境生物。这些对每个人来说都是不同的。您将需要活动点券来临时进入活动区域，或使用任务代币从代币商店购买访问权限。搜索一个野生的梦境生物，消耗1点能量，然后点击“驯服”。驯服需要一些时间，这取决于它们的稀有程度。你一次只能驯服一只，所以要小心选择。野生的梦境生物会在一段时间后消失（10-15分钟），所以不要一次消耗所有的能量，除非你打算离开一段时间，让它恢复。能量每10分钟恢复1次，开始时最多30次，但你可以增加它。",
    "Every time you search, you have a 0.5 base chance of encountering a star Dreamling. These are special variants, though really their only benefit is that they have double the max level of their regular variant. You can raise your base star chance with upgrades and Dreamling bonuses, but it's capped at 5% total.": "每次你搜索，你有0.5的基本几率遇到一个星级梦境生物。这些都是特殊的变体，尽管它们唯一的好处是它们的最大等级是常规变体的两倍。你可以通过升级和梦境生物奖励来提高你的基础星星几率，但它的上限是5%。",
    "Every time you search, you have a 0.5 base chance of encountering a star Dreamling. These are special variants, though really their only benefit is that \n                they have double the max level of their regular variant. You can raise your base star chance with upgrades and Dreamling bonuses, but it's capped at \n                5% total.": "每次你搜索，你有0.5的基本几率遇到一个星级梦境生物。这些都是特殊的变体，尽管它们唯一的好处是它们的最大等级是常规变体的两倍。你可以通过升级和梦境生物奖励来提高你的基础星星几率，但它的上限是5%。",
    "Successfully Fuse 1 Time": "成功融合 1 次",
    "Training Dreamlings (": "训练梦境生物 (",
    "Storage Dreamlings (": "存储梦境生物 (",
    "Star Chance": "星级几率",
    "Reset Taming Lock": "重置驯服锁",
    "Release": "放生",
    "No Event Access": "无活动权限",
    "Trophy Hall/Ascension": "奖杯陈列室/转生",
    "No Dreamlings ascended yet.": "暂无转生的梦境生物。",
    "x2 Research Points (15 min)": "x2 研究点数 (15 分钟)",
    "x2 Gold (15 min)": "x2 金币 (15 分钟)",
    "x2 Experience (15 min)": "x2 经验值 (15 分钟)",
    "x2 Dream Points (15 min)": "x2 梦境点数 (15 分钟)",
    "Welcome to Dreamlings Idle!": "欢迎来到 梦境生物放置!",
    "Tame 5 Common Dreamlings": "驯服 5 普通梦境生物",
    "Receive 1 random chest instantly.": "立即获得1个随机宝箱",
    "Activate the Gnome Home!": "激活侏儒之家！",
    "AKA: The Waiting Game": "又名：等待游戏",
    "Available Dreamlings In This Area": "在这一地区可获得的梦境生物",
    "Avalanche": "雪崩",
    "Double dream points gained for 15 minutes.": "在15分钟内获得双倍梦境点数。",
    "Double gold gained for 15 minutes.": "在15分钟内获得双倍金币",
    "In this tab live your current Dreamlings: your active party, your training Dreamlings and your storage.": "在这个选项卡中生活着你现有的梦境生物：你的活跃的队伍，你的训练梦境生物和你的存储。",
    "Unlock access to the event area for 6 hours.": "解锁活动区域权限6小时",
    "You must always have at least 1 Dreamling in your party!": "您的队伍中必须始终拥有1个以上的梦境生物！",
    "Trade, export, import, or make your storage BIG (5000) with the Gnome Home. Keep in mind that can't be reverted.": "交易，导出，导入，或使您的存储变大（5000）与侏儒之家。记住，这是无法恢复的。",
    "No wild Dreamlings.": "无野外梦境生物。",
    "Wild Areas/Star Dreamlings/Event Area": "野外区域/星级梦境生物/活动区域",
    "You start with the Forest area, where you can find ~50 random Dreamlings out of the 650 base ones. These are different for everyone. You will need Event Vouchers to temporarily access the Event area, or purchase access from the Token Shop with Quest Tokens. Search for a wild Dreamling, which costs 1 energy, and then click 'tame'. Taming takes some time, depending on the rarity. You can only tame 1 at a time, so choose carefully. Wild Dreamlings will disappear after some time (10-15 minutes), so don't spend all your energy at once unless you plan on leaving for a while and letting it regenerate. Energy regens 1 every 10 minutes and starts off with max 30, but you can increase this.": "你可以从森林区域开始，在那里你可以从650个基础梦境生物中找到大约50个随机梦境生物。这些对每个人来说都是不同的。您将需要活动点券来临时进入活动区域，或使用任务代币从代币商店购买访问权限。寻找一只野生梦境生物，消耗1点能量，然后点击“驯服”。驯服需要一些时间，这取决于它们的稀有程度。你一次只能驯服一只，所以要小心选择。野生的梦境生物会在一段时间后消失（10-15分钟），所以不要一次消耗所有的能量，除非你打算离开一段时间，让它恢复。能量恢复每10分钟1次，开始时最多30次，但你可以增加它。",
    "NEW!": "新!",
    "Disappears In:": "距离消失：",
    "Tame": "驯服",
    "Taming Time:": "驯服时间:",
    "Taming...": "驯服中...",
    "You don't have event access or a voucher!": "你没有活动权限或点券！",
    "Party": "队伍",
    "Total Rewards:": "总奖励:",
    "Event Voucher": "活动点券",
    "Claim Reward": "领取奖励",
    "No chests opened. Make sure you have unopened chests of this rarity!": "没有打开箱子。请确保您有未开启的此稀有度的宝箱！",
    "Confirm": "确认",
    "Are you sure you want to activate Gnome Home?\nThis will upgrade your max storage to 5000 permanently!": "确定要激活地精之家吗？这将使您的最大存储空间永久升级到5000 ！",
    "Use an Event Voucher to access the Event Area? You have 1 voucher(s) remaining.": "使用活动点券进入活动区域？您还剩 1 张点券。",
    "✨ Bonus": "✨ 加成",
    "Max Potion": "最大药水",
    "Select two Dreamlings to fuse!": "请选择2个梦境生物以融合!",
    "Tame 5 Common Dreamlings!": "驯服 5 普通梦境生物!",
    "Daily quests have been refreshed!": "日常任务已刷新!",
    "Not enough energy!": "能量不足!",
    "Clicked away too fast? Check this out.": "点击太快？看看这个。",
    "Locked": "未解锁",
    "Both fusion slots are already filled.": "两个融合槽都已经被填满了。",
    "Fusion failed: level, rarity, or rank mismatch.": "融合失败：等级、稀有度或等级不匹配。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 生物
    // "Chiplet": "小芯片",
    // "Azaleis": "杜鹃花",
    // "Abysslet": "深渊精灵",
    // "Chirpis": "唧唧",
    // "Beamis": "光束",
    // "Finery": "华服",
    // "Minotlet": "米诺特",
    // "Petalis": "花瓣",
    // "Dopplet": "多普勒",
    // "Moonbloom": "月华",
    // "Jewelis": "珠宝",
    // "Wonderis": "奇迹",
    // "Acornlet": "小橡子",
    // "Adagio": "慢板",
    // "Agatis": "阿加提斯",
    // "Albatross": "信天翁",
    // "Algaelet": "海藻",
    // "Allegro": "快板",
    // "Alpacalet": "羊驼",
    // "Alpinelet": "阿尔皮涅莱特",
    // "Altonis": "阿尔托尼斯",
    // "Amberet": "安贝雷",
    // "Amethis": "阿米什",
    // "Andante": "行板",
    // "Androidis": "安卓人",
    // "Anemone": "海葵",
    // "Arcanus": "奥卡诺斯",
    // "Ashlet": "阿什莱特",
    // "Ashwood": "灰烬木",
    // "Astralis": "星宿",
    // "Auroralis": "极光",
    // "Autumnis": "秋天",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Dreamlings": "梦境生物",
    "Dreamlings Idle": "梦境生物放置",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "???": "???",
    "🎟️": "🎟️",
    "💖": "💖",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "+": "+",
    ".": ".",
    "…": "…",
    ":": ":",
    "-": "-",
    "|": "|",
    "(": "(",
    ")": ")",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Gityx游戏': 'Gityx游戏',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    'a': 'a',
    'b': 'b',
    'c': 'c',
    'd': 'd',
    'e': 'e',
    'f': 'f',
    'g': 'g',
    'h': 'h',
    'i': 'i',
    'j': 'j',
    'k': 'k',
    'l': 'l',
    'm': 'm',
    'n': 'n',
    'o': 'o',
    'p': 'p',
    'q': 'q',
    'r': 'r',
    's': 's',
    't': 't',
    'u': 'u',
    'v': 'v',
    'w': 'w',
    'x': 'x',
    'y': 'y',
    'z': 'z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Animations: ": "动画: ",
    "Current Endgame: ": "当前终局: ",
    "Space Background: ": "太空背景: ",
    "Energy: ": "能量: ",
    "Vouchers: ": "点券: ",
    "Quest Tokens: ": "任务代币: ",
    "Research Points: ": "研究点数: ",
    "Research: ": "研究: ",
    "Bonus: ": "加成: ",
    "Chests: ": "宝箱: ",
    "Crit Chance: ": "暴击几率: ",
    "Gold: ": "金币: ",
    "Progress: ": "进度: ",
    "Next: ": "下一个: ",
    "Max Potion ": "最大药水 ",
    "Level: ": "等级: ",
    "Dream Points: ": "梦境点数: ",
    "XP/sec: ": "经验/秒: ",
    "Gold Boost: ": "金币提升: ",
    "Gold/sec: ": "金币/秒: ",
    "Owned: ": "拥有: ",
    "Quest Complete: ": "任务已完成: ",
    "Quest complete! ": "任务已完成! ",
    "Experience: +": "经验值: +",
    "Star Chance: +": "星级几率: +",
    "Taming Speed: +": "驯服速度: +",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    " (max reached)": " (以达到最大)",
    " was tamed!": " 被驯服了!",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)$/,
    /^×([\d\.]+)$/,
    /^x([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^\+([\d\.]+)\%$/,
    /^\-([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^\(([\d\.]+),([\d\.]+)\)$/,
    /^\(\-([\d\.]+),([\d\.]+)\)$/,
    /^\(\-([\d\.]+),\-([\d\.]+)\)$/,
    /^\(([\d\.]+),\-([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+) ([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.]+)\/([\d\.]+) ([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^\[([\d\.]+):([\d\.]+):([\d\.]+)\]$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^\#([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^([\d\.,]+) \(([\d\.]+)$/,
    /^x([\d\.,]+)$/,
    /^×([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^\-([\d\.,]+) \/ ([\d\.,]+)$/,
    /^\-([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Use a Max Potion to instantly level (.+) to level 100\?$/, '使用最大药水将 $1 瞬间升级到100级？'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
    [/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^\+([\d\.]+)\% elves$/, '+$1% 精灵'],
    [/^\+([\d\.]+) Instant Energy$/, '+$1 即时能量'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)h ([\d\.]+)m$/, '$1小时 $2分'],
    [/^([\d\.]+)m ([\d\.]+)s$/, '$1分钟 $2秒'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) collectible$/, '$1 收藏品'],
    [/^([\d\.,]+) collectibles$/, '$1 收藏品'],
    [/^([\d\.,]+) collectibles, ([\d\.,]+) event voucher$/, '$1 收藏品, $2 活动点券'],
    [/^([\d\.,]+) Random Chest$/, '$1 随机宝箱'],
    [/^([\d\.,]+) collectible, ([\d\.,]+) max potion$/, '$1 收藏品, $2 最大药水'],
    [/^([\d\.,]+) Gold • ([\d\.,]+) Quest Token$/, '$1 金币 • $2 任务代币'],
    [/^Level ([\d\.,]+)$/, '等级 $1'],
    [/^Legendary \(([\d\.,]+)\)$/, '传说 ($1)'],
    [/^Rare \(([\d\.,]+)\)$/, '稀有 ($1)'],
    [/^Epic \(([\d\.,]+)\)$/, '史诗 ($1)'],
    [/^Uncommon \(([\d\.,]+)\)$/, '罕见 ($1)'],
    [/^Common \(([\d\.,]+)\)$/, '普通 ($1)'],
    [/^Common T([\d\.,]+)$/, '普通 T$1'],
    [/^Uncommon T([\d\.,]+)$/, '罕见 T$1'],
    [/^Rare T([\d\.,]+)$/, '稀有 T$1'],
    [/^Epic T([\d\.,]+)$/, '史诗 T$1'],
    [/^Legendary T([\d\.,]+)$/, '传说 T$1'],
    [/^Buy ([\d\.,]+) Upgrade$/, '购买 $1 升级'],
    [/^🎉 Opened ([\d\.,]+) Chest!$/, '🎉 打开 $1 宝箱!'],
    [/^🎉 Opened ([\d\.,]+) Chests!$/, '🎉 打开 $1 宝箱!'],
    [/^Chest ([\d\.,]+)$/, '宝箱 $1'],
    [/^Slot ([\d\.,]+)$/, '槽位 $1'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^Open ([\d\.,]+) Chests!$/, '打开 $1 宝箱!'],
    [/^Tame ([\d\.,]+) Epic Dreamlings$/, '驯服 $1 史诗梦境生物'],
    [/^Tame ([\d\.,]+) Epic Dreamling$/, '驯服 $1 史诗梦境生物'],
    [/^Tame ([\d\.,]+) Rare Dreamlings$/, '驯服 $1 稀有梦境生物'],
    [/^Tame ([\d\.,]+) Rare Dreamling$/, '驯服 $1 稀有梦境生物'],
    [/^Tame ([\d\.,]+) Uncommon Dreamlings$/, '驯服 $1 罕见梦境生物'],
    [/^Tame ([\d\.,]+) Uncommon Dreamling$/, '驯服 $1 罕见梦境生物'],
    [/^Tame ([\d\.,]+) Common Dreamlings$/, '驯服 $1 普通梦境生物'],
    [/^Tame ([\d\.,]+) Common Dreamling$/, '驯服 $1 普通梦境生物'],
    [/^Tame ([\d\.,]+) Legendary Dreamlings$/, '驯服 $1 传说梦境生物'],
    [/^Tame ([\d\.,]+) Legendary Dreamling$/, '驯服 $1 传说梦境生物'],
    [/^Register ([\d\.,]+) New Dreamlings$/, '登记 $1 新的梦境生物'],
    [/^Register ([\d\.,]+) New Dreamlings!$/, '登记 $1 新的梦境生物!'],
    [/^\+([\d\.,]+) Gold, \+([\d\.,]+) Quest Token \(Claimed ([\d\.,]+) repeats, Progress: ([\d\.,]+)\)$/, '+$1 金币, +$2 任务代币 (已领取 $3 重复, 进度: $4)'],
    [/^Acornpuff \(([\d\.,]+)\-([\d\.,]+)\)$/, '橡果泡芙 ($1-$2)'],
    [/^Amberflame \(([\d\.,]+)\-([\d\.,]+)\)$/, '琥珀焰 ($1-$2)'],
    [/^Angelwing \(([\d\.,]+)\-([\d\.,]+)\)$/, '天使之翼 ($1-$2)'],
    [/^Everwhisk \(([\d\.,]+)\-([\d\.,]+)\)$/, '永恒须 ($1-$2)'],
    [/^Emberfur \(([\d\.,]+)\-([\d\.,]+)\)$/, '烬毛 ($1-$2)'],
    [/^Fogpelt \(([\d\.,]+)\-([\d\.,]+)\)$/, '雾皮 ($1-$2)'],
    [/^Windwhisper \(([\d\.,]+)\-([\d\.,]+)\)$/, '风语 ($1-$2)'],
    [/^Amberpaw \(([\d\.,]+)\-([\d\.,]+)\)$/, '琥珀爪 ($1-$2)'],
    [/^Autumnmist \(([\d\.,]+)\-([\d\.,]+)\)$/, '秋雾 ($1-$2)'],
    [/^Base \(([\d\.,]+)\-([\d\.,]+)\)$/, '基础 ($1-$2)'],
    [/^Level ([\d\.,]+) \(([\d\.,]+) \/ ([\d\.,]+)\)$/, '等级 $1 ($2 \/ $3)'],
    [/^Level ([\d\.,]+) \(\-([\d\.,]+) \/ ([\d\.,]+)\)$/, '等级 $1 (-$2 \/ $3)'],
    [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^([\d\.,]+) \/ ([\d\.,]+) \(Next in ([\d\.,]+):([\d\.,]+)\)$/, '$1 \/ $2  (下一个还需 $3:$4)'],
    [/^([\d\.,]+) \/ ([\d\.,]+) \(next chest in ([\d\.,]+):([\d\.,]+)\)$/, '$1 \/ $2  (下一个宝箱还需 $3:$4)'],
    [/^Event ([\d\.,]+)\/([\d\.,]+)$/, '活动 $2 年 $1 月'],
    [/^Chests: ([\d\.,]+) \/ ([\d\.,]+) \(next chest in ([\d\.,]+):([\d\.,]+)\)$/, '宝箱: $1 \/ $2 (下一个宝箱还有 $3:$4)'],
    [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Completed repeats: (.+) • Remaining: (.+)$/, '已完成重复: $1 • 剩余: $2'],
    [/^Cost: (.+) Quest Tokens$/, '成本：$1 任务代币'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);